# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import emulator_pb2 as emulator__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in emulator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SfpEmulatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/emulator.SfpEmulatorService/Create',
                request_serializer=emulator__pb2.CreateRequest.SerializeToString,
                response_deserializer=emulator__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/emulator.SfpEmulatorService/Delete',
                request_serializer=emulator__pb2.DeleteRequest.SerializeToString,
                response_deserializer=emulator__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/emulator.SfpEmulatorService/Read',
                request_serializer=emulator__pb2.ReadRequest.SerializeToString,
                response_deserializer=emulator__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/emulator.SfpEmulatorService/Write',
                request_serializer=emulator__pb2.WriteRequest.SerializeToString,
                response_deserializer=emulator__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.GetInfo = channel.unary_unary(
                '/emulator.SfpEmulatorService/GetInfo',
                request_serializer=emulator__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=emulator__pb2.GetInfoResponse.FromString,
                _registered_method=True)
        self.UpdateInfo = channel.unary_unary(
                '/emulator.SfpEmulatorService/UpdateInfo',
                request_serializer=emulator__pb2.UpdateInfoRequest.SerializeToString,
                response_deserializer=emulator__pb2.UpdateInfoResponse.FromString,
                _registered_method=True)
        self.Monitor = channel.unary_stream(
                '/emulator.SfpEmulatorService/Monitor',
                request_serializer=emulator__pb2.MonitorRequest.SerializeToString,
                response_deserializer=emulator__pb2.MonitorResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/emulator.SfpEmulatorService/List',
                request_serializer=emulator__pb2.ListRequest.SerializeToString,
                response_deserializer=emulator__pb2.ListResponse.FromString,
                _registered_method=True)


class SfpEmulatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Monitor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SfpEmulatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=emulator__pb2.CreateRequest.FromString,
                    response_serializer=emulator__pb2.CreateResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=emulator__pb2.DeleteRequest.FromString,
                    response_serializer=emulator__pb2.DeleteResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=emulator__pb2.ReadRequest.FromString,
                    response_serializer=emulator__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=emulator__pb2.WriteRequest.FromString,
                    response_serializer=emulator__pb2.WriteResponse.SerializeToString,
            ),
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=emulator__pb2.GetInfoRequest.FromString,
                    response_serializer=emulator__pb2.GetInfoResponse.SerializeToString,
            ),
            'UpdateInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInfo,
                    request_deserializer=emulator__pb2.UpdateInfoRequest.FromString,
                    response_serializer=emulator__pb2.UpdateInfoResponse.SerializeToString,
            ),
            'Monitor': grpc.unary_stream_rpc_method_handler(
                    servicer.Monitor,
                    request_deserializer=emulator__pb2.MonitorRequest.FromString,
                    response_serializer=emulator__pb2.MonitorResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=emulator__pb2.ListRequest.FromString,
                    response_serializer=emulator__pb2.ListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emulator.SfpEmulatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('emulator.SfpEmulatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SfpEmulatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emulator.SfpEmulatorService/Create',
            emulator__pb2.CreateRequest.SerializeToString,
            emulator__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emulator.SfpEmulatorService/Delete',
            emulator__pb2.DeleteRequest.SerializeToString,
            emulator__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emulator.SfpEmulatorService/Read',
            emulator__pb2.ReadRequest.SerializeToString,
            emulator__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emulator.SfpEmulatorService/Write',
            emulator__pb2.WriteRequest.SerializeToString,
            emulator__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emulator.SfpEmulatorService/GetInfo',
            emulator__pb2.GetInfoRequest.SerializeToString,
            emulator__pb2.GetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emulator.SfpEmulatorService/UpdateInfo',
            emulator__pb2.UpdateInfoRequest.SerializeToString,
            emulator__pb2.UpdateInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Monitor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/emulator.SfpEmulatorService/Monitor',
            emulator__pb2.MonitorRequest.SerializeToString,
            emulator__pb2.MonitorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emulator.SfpEmulatorService/List',
            emulator__pb2.ListRequest.SerializeToString,
            emulator__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
